services:
    db:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - go_postgres_data:/var/lib/postgresql/data
        restart: always
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
            interval: 5s
            timeout: 10s
            retries: 5
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '3'

volumes:
    go_postgres_data: